export const FRUITS_DATAS = [
  "Pomme Granny Smith",
  "Pomme Gala",
  "Pomme Red Delicious",
  "Pomme Fuji",
  "Pomme Honeycrisp",
  "Pomme Pink Lady",
  "Pomme Golden Delicious",
  "Pomme McIntosh",
  "Pêche jaune",
  "Pêche blanche",
  "Pêche de vigne",
  "Nectarine",
  "Abricot",
  "Prune",
  "Cerise douce",
  "Cerise acide",
];
